services:
  - type: web
    name: momentoooo
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: momentoooo-db
          property: connectionString

databases:
  - name: momentoooo-db
    plan: free
